CREATE DATABASE PRUEBA;---CREACION BASE DE DATOS

USE PRUEBA;
---------TABLAS
CREATE TABLE [DBO].[CLIENTES](
	[CLIENTE] [INT] PRIMARY KEY,
	[NOMBRE_CLIENTE] [VARCHAR](50) NULL,
	[DIRECCION] [VARCHAR](50) NULL
	);

CREATE TABLE [DBO].[PRODUCTOS](
	[PRODUCTO] [INT] PRIMARY KEY,
	[NOMBRE_PRODUCTO] [VARCHAR](50) NULL,
	[VALOR] [FLOAT] NULL
	);

CREATE TABLE [DBO].[CABEZA_FACTURA](
	[NUMERO] [INT] PRIMARY KEY,
	[FECHA] [DATETIME] NULL,
	[CLIENTE] [INT] NULL,
	[TOTAL] [FLOAT] NULL
	);

CREATE TABLE [DBO].[DETALLE_FACTURA](
	[NUMERO] [INT] PRIMARY KEY,
	[PRODUCTO] [INT] NULL,
	[CANTIDAD] [INT] NULL,
	[VALOR] [FLOAT] NULL
	);

	-----INSERCIONES

INSERT [DBO].[CABEZA_FACTURA] ([NUMERO], [FECHA], [CLIENTE], [TOTAL]) VALUES (1, CAST(N'2023-01-24T00:00:00.000' AS DATETIME), 1110565292, 20000)
GO
INSERT [DBO].[CLIENTES] ([CLIENTE], [NOMBRE_CLIENTE], [DIRECCION]) VALUES (1110565292, N'JOSE JULIAN GOMEZ GOMEZ', N'CARRERA 6 #19-17 EL CARMEN')
GO
INSERT [DBO].[DETALLE_FACTURA] ([NUMERO], [PRODUCTO], [CANTIDAD], [VALOR]) VALUES (1, 1, 1, 20000)
GO
INSERT [DBO].[PRODUCTOS] ([PRODUCTO], [NOMBRE_PRODUCTO], [VALOR]) VALUES (1, N'MOUSE', 20000)

---------------RELACIONES
ALTER TABLE [DBO].[CABEZA_FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE] FOREIGN KEY([CLIENTE])
REFERENCES [DBO].[CLIENTES] ([CLIENTE])
GO
ALTER TABLE [DBO].[CABEZA_FACTURA] CHECK CONSTRAINT [FK_CLIENTE]
GO
ALTER TABLE [DBO].[DETALLE_FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_NUMERO] FOREIGN KEY([NUMERO])
REFERENCES [DBO].[CABEZA_FACTURA] ([NUMERO])
GO
ALTER TABLE [DBO].[DETALLE_FACTURA] CHECK CONSTRAINT [FK_NUMERO]
GO
ALTER TABLE [DBO].[DETALLE_FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTO] FOREIGN KEY([PRODUCTO])
REFERENCES [DBO].[PRODUCTOS] ([PRODUCTO])
GO
ALTER TABLE [DBO].[DETALLE_FACTURA] CHECK CONSTRAINT [FK_PRODUCTO]
